Edited test pipeline

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -34,6 +34,7 @@ jobs:
     name: Unit tests
     runs-on: ubuntu-latest
     needs: lint
+    continue-on-error: true
     steps:
       - name: Checkout repository
         uses: actions/checkout@v1
@@ -48,18 +49,21 @@ jobs:
           python -m pip install --upgrade pip
           python -m pip install --upgrade wheel pytest
       
-      # - name: Verify tests execution readiness
-      #   run: |
-      #     exec_tests=$(find tests -maxdepth 1 -type f -name 'test*' > /dev/null 2>&1; echo $?)
-      #     exit $exec_tests
-
-      - name: Run tests
-        # if: ${{ success() }}
+      - name: Verify tests execution readiness
         run: |
           exec_tests=$(find tests -maxdepth 1 -type f -name 'test*' > /dev/null 2>&1; echo $?)
-          if test $exec_tests -eq 0
-          then
-            pytest --record-mode=none tests/test* -vv
-          else
-            echo "Files not found: skipping tests execution"
-          fi
+          exit $exec_tests
+
+      - name: Run tests
+        if: ${{ success() }}
+        run: |
+          pytest --record-mode=none tests/test* -vv
+
+        # run: |
+        #   exec_tests=$(find tests -maxdepth 1 -type f -name 'test*' > /dev/null 2>&1; echo $?)
+        #   if test $exec_tests -eq 0
+        #   then
+        #     pytest --record-mode=none tests/test* -vv
+        #   else
+        #     echo "Files not found: skipping tests execution"
+        #   fi
